package org.mnode.jot4j.dynamodb.mapper;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import net.fortuna.ical4j.model.component.VAlarm;

@EqualsAndHashCode(callSuper = true)
@Data
@NoArgsConstructor
public class Alarm extends AbstractMapper {

    @DynamoDBAttribute(attributeName = "Uid")
    @DynamoDBAutoGeneratedKey
    private String uid;

    @DynamoDBAttribute(attributeName = "Data")
    @DynamoDBTypeConverted(converter = VAlarmConverter.class)
    private VAlarm data;

    @DynamoDBAttribute(attributeName = "ComponentUid")
    private String componentUid;

    private String componentType;

    @Override
    @DynamoDBHashKey(attributeName = "PK")
    public String getPK() {
        return "GROUP#" + getGroupId() + "#ALARM#" + uid;
    }

    @Override
    @DynamoDBRangeKey(attributeName = "SK")
    public String getSK() {
        return getPK();
    }

    @Override
    @DynamoDBAttribute(attributeName = "TYPE")
    public String getType() {
        return "ALARM";
    }

    @DynamoDBIndexHashKey(attributeName = "GSI3_PK", globalSecondaryIndexName = "GSI3")
    public String getGSI3PK() {
        return "GROUP#" + getGroupId() + "#" + componentType + "#" + getComponentUid();
    }

    @DynamoDBIndexRangeKey(attributeName = "GSI3_SK", globalSecondaryIndexName = "GSI3")
    public String getGSI3SK() {
        return getSK();
    }
}
